namespace NumbersInWords;

public partial class NumberInWordsUnitTests
{
    private static IList<(decimal, string)> _21To99Source = new List<(decimal, string)>
    {
        (21, "twenty one"),
        (22, "twenty two"),
        (23, "twenty three"),
        (24, "twenty four"),
        (25, "twenty five"),
        (26, "twenty six"),
        (27, "twenty seven"),
        (28, "twenty eight"),
        (29, "twenty nine"),
        (30, "thirty"),
        (31, "thirty one"),
        (32, "thirty two"),
        (33, "thirty three"),
        (34, "thirty four"),
        (35, "thirty five"),
        (36, "thirty six"),
        (37, "thirty seven"),
        (38, "thirty eight"),
        (39, "thirty nine"),
        (40, "forty"),
        (41, "forty one"),
        (42, "forty two"),
        (43, "forty three"),
        (44, "forty four"),
        (45, "forty five"),
        (46, "forty six"),
        (47, "forty seven"),
        (48, "forty eight"),
        (49, "forty nine"),
        (50, "fifty"),
        (51, "fifty one"),
        (52, "fifty two"),
        (53, "fifty three"),
        (54, "fifty four"),
        (55, "fifty five"),
        (56, "fifty six"),
        (57, "fifty seven"),
        (58, "fifty eight"),
        (59, "fifty nine"),
        (60, "sixty"),
        (61, "sixty one"),
        (62, "sixty two"),
        (63, "sixty three"),
        (64, "sixty four"),
        (65, "sixty five"),
        (66, "sixty six"),
        (67, "sixty seven"),
        (68, "sixty eight"),
        (69, "sixty nine"),
        (70, "seventy"),
        (71, "seventy one"),
        (72, "seventy two"),
        (73, "seventy three"),
        (74, "seventy four"),
        (75, "seventy five"),
        (76, "seventy six"),
        (77, "seventy seven"),
        (78, "seventy eight"),
        (79, "seventy nine"),
        (80, "eighty"),
        (81, "eighty one"),
        (82, "eighty two"),
        (83, "eighty three"),
        (84, "eighty four"),
        (85, "eighty five"),
        (86, "eighty six"),
        (87, "eighty seven"),
        (88, "eighty eight"),
        (89, "eighty nine"),
        (90, "ninety"),
        (91, "ninety one"),
        (92, "ninety two"),
        (93, "ninety three"),
        (94, "ninety four"),
        (95, "ninety five"),
        (96, "ninety six"),
        (97, "ninety seven"),
        (98, "ninety eight"),
        (99, "ninety nine")
    };

    private static IList<(decimal, string)> _100To999Source = new List<(decimal, string)>
    {
        (100, "one hundred"),
        (101, "one hundred one"),
        (102, "one hundred two"),
        (103, "one hundred three"),
        (104, "one hundred four"),
        (105, "one hundred five"),
        (106, "one hundred six"),
        (107, "one hundred seven"),
        (108, "one hundred eight"),
        (109, "one hundred nine"),
        (110, "one hundred ten"),
        (111, "one hundred eleven"),
        (112, "one hundred twelve"),
        (113, "one hundred thirteen"),
        (114, "one hundred fourteen"),
        (115, "one hundred fifteen"),
        (116, "one hundred sixteen"),
        (117, "one hundred seventeen"),
        (118, "one hundred eighteen"),
        (119, "one hundred nineteen"),
        (120, "one hundred twenty"),
        (121, "one hundred twenty one"),
        (122, "one hundred twenty two"),
        (123, "one hundred twenty three"),
        (124, "one hundred twenty four"),
        (125, "one hundred twenty five"),
        (126, "one hundred twenty six"),
        (127, "one hundred twenty seven"),
        (128, "one hundred twenty eight"),
        (129, "one hundred twenty nine"),
        (130, "one hundred thirty"),
        (131, "one hundred thirty one"),
        (132, "one hundred thirty two"),
        (133, "one hundred thirty three"),
        (134, "one hundred thirty four"),
        (135, "one hundred thirty five"),
        (136, "one hundred thirty six"),
        (137, "one hundred thirty seven"),
        (138, "one hundred thirty eight"),
        (139, "one hundred thirty nine"),
        (140, "one hundred forty"),
        (141, "one hundred forty one"),
        (142, "one hundred forty two"),
        (143, "one hundred forty three"),
        (144, "one hundred forty four"),
        (145, "one hundred forty five"),
        (146, "one hundred forty six"),
        (147, "one hundred forty seven"),
        (148, "one hundred forty eight"),
        (149, "one hundred forty nine"),
        (150, "one hundred fifty"),
        (151, "one hundred fifty one"),
        (152, "one hundred fifty two"),
        (153, "one hundred fifty three"),
        (154, "one hundred fifty four"),
        (155, "one hundred fifty five"),
        (156, "one hundred fifty six"),
        (157, "one hundred fifty seven"),
        (158, "one hundred fifty eight"),
        (261, "two hundred sixty one"),
        (262, "two hundred sixty two"),
        (263, "two hundred sixty three"),
        (264, "two hundred sixty four"),
        (265, "two hundred sixty five"),
        (266, "two hundred sixty six"),
        (267, "two hundred sixty seven"),
        (268, "two hundred sixty eight"),
        (269, "two hundred sixty nine"),
        (270, "two hundred seventy"),
        (271, "two hundred seventy one"),
        (272, "two hundred seventy two"),
        (273, "two hundred seventy three"),
        (274, "two hundred seventy four"),
        (275, "two hundred seventy five"),
        (276, "two hundred seventy six"),
        (277, "two hundred seventy seven"),
        (278, "two hundred seventy eight"),
        (279, "two hundred seventy nine"),
        (280, "two hundred eighty"),
        (281, "two hundred eighty one"),
        (282, "two hundred eighty two"),
        (283, "two hundred eighty three"),
        (384, "three hundred eighty four"),
        (385, "three hundred eighty five"),
        (386, "three hundred eighty six"),
        (387, "three hundred eighty seven"),
        (388, "three hundred eighty eight"),
        (389, "three hundred eighty nine"),
        (390, "three hundred ninety"),
        (391, "three hundred ninety one"),
        (392, "three hundred ninety two"),
        (493, "four hundred ninety three"),
        (494, "four hundred ninety four"),
        (495, "four hundred ninety five"),
        (496, "four hundred ninety six"),
        (497, "four hundred ninety seven"),
        (498, "four hundred ninety eight"),
        (499, "four hundred ninety nine"),
        (500, "five hundred"),
        (632, "six hundred thirty two"),
        (633, "six hundred thirty three"),
        (634, "six hundred thirty four"),
        (635, "six hundred thirty five"),
        (636, "six hundred thirty six"),
        (637, "six hundred thirty seven"),
        (638, "six hundred thirty eight"),
        (639, "six hundred thirty nine"),
        (640, "six hundred forty"),
        (641, "six hundred forty one"),
        (642, "six hundred forty two"),
        (643, "six hundred forty three"),
        (644, "six hundred forty four"),
        (645, "six hundred forty five"),
        (646, "six hundred forty six"),
        (647, "six hundred forty seven"),
        (648, "six hundred forty eight"),
        (649, "six hundred forty nine"),
        (650, "six hundred fifty"),
        (651, "six hundred fifty one"),
        (652, "six hundred fifty two"),
        (653, "six hundred fifty three"),
        (654, "six hundred fifty four"),
        (655, "six hundred fifty five"),
        (656, "six hundred fifty six"),
        (657, "six hundred fifty seven"),
        (658, "six hundred fifty eight"),
        (659, "six hundred fifty nine"),
        (660, "six hundred sixty"),
        (661, "six hundred sixty one"),
        (662, "six hundred sixty two"),
        (663, "six hundred sixty three"),
        (664, "six hundred sixty four"),
        (665, "six hundred sixty five"),
        (666, "six hundred sixty six"),
        (667, "six hundred sixty seven"),
        (668, "six hundred sixty eight"),
        (669, "six hundred sixty nine"),
        (670, "six hundred seventy"),
        (671, "six hundred seventy one"),
        (672, "six hundred seventy two"),
        (673, "six hundred seventy three"),
        (674, "six hundred seventy four"),
        (675, "six hundred seventy five"),
        (676, "six hundred seventy six"),
        (677, "six hundred seventy seven"),
        (778, "seven hundred seventy eight"),
        (779, "seven hundred seventy nine"),
        (780, "seven hundred eighty"),
        (781, "seven hundred eighty one"),
        (782, "seven hundred eighty two"),
        (783, "seven hundred eighty three"),
        (784, "seven hundred eighty four"),
        (785, "seven hundred eighty five"),
        (786, "seven hundred eighty six"),
        (787, "seven hundred eighty seven"),
        (788, "seven hundred eighty eight"),
        (789, "seven hundred eighty nine"),
        (790, "seven hundred ninety"),
        (791, "seven hundred ninety one"),
        (792, "seven hundred ninety two"),
        (793, "seven hundred ninety three"),
        (794, "seven hundred ninety four"),
        (795, "seven hundred ninety five"),
        (796, "seven hundred ninety six"),
        (797, "seven hundred ninety seven"),
        (798, "seven hundred ninety eight"),
        (799, "seven hundred ninety nine"),
        (800, "eight hundred"),
        (801, "eight hundred one"),
        (802, "eight hundred two"),
        (803, "eight hundred three"),
        (804, "eight hundred four"),
        (805, "eight hundred five"),
        (806, "eight hundred six"),
        (807, "eight hundred seven"),
        (808, "eight hundred eight"),
        (809, "eight hundred nine"),
        (810, "eight hundred ten"),
        (811, "eight hundred eleven"),
        (812, "eight hundred twelve"),
        (813, "eight hundred thirteen"),
        (814, "eight hundred fourteen"),
        (815, "eight hundred fifteen"),
        (816, "eight hundred sixteen"),
        (817, "eight hundred seventeen"),
        (818, "eight hundred eighteen"),
        (819, "eight hundred nineteen"),
        (820, "eight hundred twenty"),
        (821, "eight hundred twenty one"),
        (822, "eight hundred twenty two"),
        (823, "eight hundred twenty three"),
        (824, "eight hundred twenty four"),
        (825, "eight hundred twenty five"),
        (959, "nine hundred fifty nine"),
        (960, "nine hundred sixty"),
        (961, "nine hundred sixty one"),
        (962, "nine hundred sixty two"),
        (963, "nine hundred sixty three"),
        (964, "nine hundred sixty four"),
        (965, "nine hundred sixty five"),
        (966, "nine hundred sixty six"),
        (967, "nine hundred sixty seven"),
        (968, "nine hundred sixty eight"),
        (969, "nine hundred sixty nine"),
        (970, "nine hundred seventy"),
        (971, "nine hundred seventy one"),
        (972, "nine hundred seventy two"),
        (973, "nine hundred seventy three"),
        (974, "nine hundred seventy four"),
        (975, "nine hundred seventy five"),
        (976, "nine hundred seventy six"),
        (977, "nine hundred seventy seven"),
        (978, "nine hundred seventy eight"),
        (979, "nine hundred seventy nine"),
        (980, "nine hundred eighty"),
        (981, "nine hundred eighty one"),
        (982, "nine hundred eighty two"),
        (983, "nine hundred eighty three"),
        (984, "nine hundred eighty four"),
        (985, "nine hundred eighty five"),
        (986, "nine hundred eighty six"),
        (987, "nine hundred eighty seven"),
        (988, "nine hundred eighty eight"),
        (989, "nine hundred eighty nine"),
        (990, "nine hundred ninety"),
        (991, "nine hundred ninety one"),
        (992, "nine hundred ninety two"),
        (993, "nine hundred ninety three"),
        (994, "nine hundred ninety four"),
        (995, "nine hundred ninety five"),
        (996, "nine hundred ninety six"),
        (997, "nine hundred ninety seven"),
        (998, "nine hundred ninety eight"),
        (999, "nine hundred ninety nine")
    };

    private static IList<(decimal, string)> _1000To9999Source = new List<(decimal, string)>
    {
        //a few random values from 1000 to 999999
        (1001, "one thousand one"),
        (1002, "one thousand two"),
        (1003, "one thousand three"),
        (1004, "one thousand four"),
        (1005, "one thousand five"),
        (1006, "one thousand six"),
        (1007, "one thousand seven"),
        (1008, "one thousand eight"),
        (1009, "one thousand nine"),
        (1010, "one thousand ten"),
        (1011, "one thousand eleven"),
        (1012, "one thousand twelve"),
        (1013, "one thousand thirteen"),
        (1014, "one thousand fourteen"),
        (1015, "one thousand fifteen"),
        (1016, "one thousand sixteen"),
        (1017, "one thousand seventeen"),
        (1018, "one thousand eighteen"),
        (1019, "one thousand nineteen"),
        (1020, "one thousand twenty"),
        (1021, "one thousand twenty one"),
        (1022, "one thousand twenty two"),
        (1023, "one thousand twenty three"),
        (1024, "one thousand twenty four"),
        (1025, "one thousand twenty five"),
        (2434, "two thousand four hundred thirty four"),
        (2435, "two thousand four hundred thirty five"),
        (2436, "two thousand four hundred thirty six"),
        (2437, "two thousand four hundred thirty seven"),
        (2438, "two thousand four hundred thirty eight"),
        (2439, "two thousand four hundred thirty nine"),
        (2440, "two thousand four hundred forty"),
        (2441, "two thousand four hundred forty one"),
        (2442, "two thousand four hundred forty two"),
        (2443, "two thousand four hundred forty three"),
        (2444, "two thousand four hundred forty four"),
        (2445, "two thousand four hundred forty five"),
        (2446, "two thousand four hundred forty six"),
        (2447, "two thousand four hundred forty seven"),
        (2448, "two thousand four hundred forty eight"),
        (2449, "two thousand four hundred forty nine"),
        (2450, "two thousand four hundred fifty"),
        (2451, "two thousand four hundred fifty one"),
        (2452, "two thousand four hundred fifty two"),
        (2453, "two thousand four hundred fifty three"),
        (2454, "two thousand four hundred fifty four"),
        (2455, "two thousand four hundred fifty five"),
        (2456, "two thousand four hundred fifty six"),
        (2457, "two thousand four hundred fifty seven"),
        (2458, "two thousand four hundred fifty eight"),
        (2459, "two thousand four hundred fifty nine"),
        (2460, "two thousand four hundred sixty"),
        (2461, "two thousand four hundred sixty one"),
        (2462, "two thousand four hundred sixty two"),
        (2463, "two thousand four hundred sixty three"),
        (2464, "two thousand four hundred sixty four"),
        (2465, "two thousand four hundred sixty five"),
        (2466, "two thousand four hundred sixty six"),
        (2467, "two thousand four hundred sixty seven"),
        (2468, "two thousand four hundred sixty eight"),
        (2469, "two thousand four hundred sixty nine"),
        (3650, "three thousand six hundred fifty"),
        (3651, "three thousand six hundred fifty one"),
        (3652, "three thousand six hundred fifty two"),
        (3653, "three thousand six hundred fifty three"),
        (3654, "three thousand six hundred fifty four"),
        (3655, "three thousand six hundred fifty five"),
        (3656, "three thousand six hundred fifty six"),
        (3657, "three thousand six hundred fifty seven"),
        (3658, "three thousand six hundred fifty eight"),
        (3659, "three thousand six hundred fifty nine"),
        (3660, "three thousand six hundred sixty"),
        (3661, "three thousand six hundred sixty one"),
        (3662, "three thousand six hundred sixty two"),
        (3663, "three thousand six hundred sixty three"),
        (3664, "three thousand six hundred sixty four"),
        (3665, "three thousand six hundred sixty five"),
        (3666, "three thousand six hundred sixty six"),
        (3667, "three thousand six hundred sixty seven"),
        (3668, "three thousand six hundred sixty eight"),
        (3669, "three thousand six hundred sixty nine"),
        (3670, "three thousand six hundred seventy"),
        (3671, "three thousand six hundred seventy one"),
        (3672, "three thousand six hundred seventy two"),
        (3673, "three thousand six hundred seventy three"),
        (3674, "three thousand six hundred seventy four"),
        (3675, "three thousand six hundred seventy five"),
        (3676, "three thousand six hundred seventy six"),
        (3677, "three thousand six hundred seventy seven"),
        (3678, "three thousand six hundred seventy eight"),
        (3679, "three thousand six hundred seventy nine"),
        (3680, "three thousand six hundred eighty"),
        (3681, "three thousand six hundred eighty one"),
        (3682, "three thousand six hundred eighty two"),
        (3683, "three thousand six hundred eighty three"),
        (3684, "three thousand six hundred eighty four"),
        (3685, "three thousand six hundred eighty five"),
        (4754, "four thousand seven hundred fifty four"),
        (4755, "four thousand seven hundred fifty five"),
        (4756, "four thousand seven hundred fifty six"),
        (4757, "four thousand seven hundred fifty seven"),
        (4758, "four thousand seven hundred fifty eight"),
        (4759, "four thousand seven hundred fifty nine"),
        (4760, "four thousand seven hundred sixty"),
        (4761, "four thousand seven hundred sixty one"),
        (4762, "four thousand seven hundred sixty two"),
        (4763, "four thousand seven hundred sixty three"),
        (4764, "four thousand seven hundred sixty four"),
        (4765, "four thousand seven hundred sixty five"),
        (4766, "four thousand seven hundred sixty six"),
        (4767, "four thousand seven hundred sixty seven"),
        (4768, "four thousand seven hundred sixty eight"),
        (4769, "four thousand seven hundred sixty nine"),
        (4770, "four thousand seven hundred seventy"),
        (4771, "four thousand seven hundred seventy one"),
        (4772, "four thousand seven hundred seventy two"),
        (4773, "four thousand seven hundred seventy three"),
        (4774, "four thousand seven hundred seventy four"),
        (4775, "four thousand seven hundred seventy five"),
        (4776, "four thousand seven hundred seventy six"),
        (4777, "four thousand seven hundred seventy seven"),
        (4778, "four thousand seven hundred seventy eight"),
        (4779, "four thousand seven hundred seventy nine"),
        (4780, "four thousand seven hundred eighty"),
        (4781, "four thousand seven hundred eighty one"),
        (4782, "four thousand seven hundred eighty two"),
        (4783, "four thousand seven hundred eighty three"),
        (4784, "four thousand seven hundred eighty four"),
        (4785, "four thousand seven hundred eighty five"),
        (4786, "four thousand seven hundred eighty six"),
        (4787, "four thousand seven hundred eighty seven"),
        (4788, "four thousand seven hundred eighty eight"),
        (4789, "four thousand seven hundred eighty nine"),
        (5890,  "five thousand eight hundred ninety"),
        (5891,  "five thousand eight hundred ninety one"),
        (6992,  "six thousand nine hundred ninety two"),
        (6993,  "six thousand nine hundred ninety three"),
        (6994,  "six thousand nine hundred ninety four"),
        (6995,  "six thousand nine hundred ninety five"),
        (6996,  "six thousand nine hundred ninety six"),
        (6997,  "six thousand nine hundred ninety seven"),
        (6998,  "six thousand nine hundred ninety eight"),
        (6999,  "six thousand nine hundred ninety nine"),
        (7000,  "seven thousand"),
        (7001,  "seven thousand one"),
        (7002,  "seven thousand two"),
        (7003,  "seven thousand three"),
        (7004,  "seven thousand four"),
        (7005,  "seven thousand five"),
        (7006,  "seven thousand six"),
        (7007,  "seven thousand seven"),
        (7008,  "seven thousand eight"),
        (7009,  "seven thousand nine"),
        (7010,  "seven thousand ten"),
        (7011,  "seven thousand eleven"),
        (7012,  "seven thousand twelve"),
        (7013,  "seven thousand thirteen"),
        (7014,  "seven thousand fourteen"),
        (7015,  "seven thousand fifteen"),
        (7016,  "seven thousand sixteen"),
        (7017,  "seven thousand seventeen"),
        (7018,  "seven thousand eighteen"),
        (7019,  "seven thousand nineteen"),
        (7020,  "seven thousand twenty"),
        (7021,  "seven thousand twenty one"),
        (7022,  "seven thousand twenty two"),
        (7023,  "seven thousand twenty three"),
        (7024,  "seven thousand twenty four"),
        (7025,  "seven thousand twenty five"),
        (7026,  "seven thousand twenty six"),
        (7027,  "seven thousand twenty seven"),
        (7028,  "seven thousand twenty eight"),
        (7029,  "seven thousand twenty nine"),
        (7030,  "seven thousand thirty"),
        (8531,  "eight thousand five hundred thirty one"),
        (8532,  "eight thousand five hundred thirty two"),
        (8533,  "eight thousand five hundred thirty three"),
        (8534,  "eight thousand five hundred thirty four"),
        (8535,  "eight thousand five hundred thirty five"),
        (8536,  "eight thousand five hundred thirty six"),
        (8537,  "eight thousand five hundred thirty seven"),
        (8538,  "eight thousand five hundred thirty eight"),
        (8539,  "eight thousand five hundred thirty nine"),
        (8540,  "eight thousand five hundred forty"),
        (8541,  "eight thousand five hundred forty one"),
        (8542,  "eight thousand five hundred forty two"),
        (8543,  "eight thousand five hundred forty three"),
        (8544,  "eight thousand five hundred forty four"),
        (8545,  "eight thousand five hundred forty five"),
        (8546,  "eight thousand five hundred forty six"),
        (8547,  "eight thousand five hundred forty seven"),
        (8548,  "eight thousand five hundred forty eight"),
        (8549,  "eight thousand five hundred forty nine"),
        (8550,  "eight thousand five hundred fifty"),
        (8551,  "eight thousand five hundred fifty one"),
        (8552,  "eight thousand five hundred fifty two"),
        (9553,  "nine thousand five hundred fifty three"),
        (9554,  "nine thousand five hundred fifty four"),
        (9555,  "nine thousand five hundred fifty five"),
        (9556,  "nine thousand five hundred fifty six"),
        (9557,  "nine thousand five hundred fifty seven"),
        (9558,  "nine thousand five hundred fifty eight"),
        (9559,  "nine thousand five hundred fifty nine"),
        (9560,  "nine thousand five hundred sixty"),
        (9561,  "nine thousand five hundred sixty one"),
        (9562,  "nine thousand five hundred sixty two"),
        (9563,  "nine thousand five hundred sixty three"),
        (9564,  "nine thousand five hundred sixty four"),
        (9565,  "nine thousand five hundred sixty five"),
        (9566,  "nine thousand five hundred sixty six"),
        (9567,  "nine thousand five hundred sixty seven"),
        (9568,  "nine thousand five hundred sixty eight"),
        (9569,  "nine thousand five hundred sixty nine"),
        (9570,  "nine thousand five hundred seventy"),
        (9571,  "nine thousand five hundred seventy one"),
        (9572,  "nine thousand five hundred seventy two"),
        (9573,  "nine thousand five hundred seventy three"),
        (9574,  "nine thousand five hundred seventy four"),
        (9575,  "nine thousand five hundred seventy five"),
        (9576,  "nine thousand five hundred seventy six"),
        (9577,  "nine thousand five hundred seventy seven"),
        (9578,  "nine thousand five hundred seventy eight"),
        (9579,  "nine thousand five hundred seventy nine"),
        (9580,  "nine thousand five hundred eighty"),
        (9581,  "nine thousand five hundred eighty one"),
        (9582,  "nine thousand five hundred eighty two"),
        (9583,  "nine thousand five hundred eighty three"),
        (9584,  "nine thousand five hundred eighty four"),
        (9585,  "nine thousand five hundred eighty five"),
        (9586,  "nine thousand five hundred eighty six"),
        (9999,  "nine thousand nine hundred ninety nine"),
    };
}